---

galaxy_info:
  author: Mathis
  role_name: openssh
  namespace: mbellamy
  description: Common tools
  company: none
  license: MLP2
  galaxy_tags:
    - common_tools
  min_ansible_version: '2.10'
dependencies: []
