---

galaxy_info:
  author: Mathis
  role_name: vaultwarden
  namespace: mbellamy
  description: To install vaultwarden
  company: none
  license: MLP2
  galaxy_tags:
    - vaultwarden
  min_ansible_version: '2.10'
dependencies: []
