---

galaxy_info:
  author: Mathis
  role_name: caddy
  namespace: mbellamy
  description: To install caddy
  company: none
  license: MLP2
  galaxy_tags:
    - caddy
  min_ansible_version: '2.10'
dependencies: []
