---

- name: "USERS - Create groups"
  ansible.builtin.group:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] | default('present') }}"
  loop: "{{ users_groups_list }}"
  become: true

- name: "USERS - Create groups sudoers file"
  ansible.builtin.template:
    src: 'etc/sudoers.d/sudoers.j2'
    dest: "/etc/sudoers.d/{{ item['name'] }}"
    owner: root
    group: root
    mode: "0o440"
  loop: "{{ users_groups_list }}"
  when: item['rights'] is defined and item['rights'] != [] and item['state'] | default('present') != 'absent'
  become: true

- name: "USERS - Create users"
  ansible.builtin.user:
    name: "{{ item['name'] }}"
    password: "{{ (item['password'] | password_hash('sha512')) | default('!') }}"
    groups: "{{ item['groups'] | join(',') }}"
    shell: "/bin/bash"
    state: "{{ item['state'] | default('present') }}"
  loop: "{{ users_users_list }}"
  become: true

- name: "USERS - Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "/home/{{ item['name'] }}/.ssh"
    owner: "{{ item['name'] }}"
    group: "{{ item['name'] }}"
    mode: "0o700"
    state: directory
  loop: "{{ users_users_list }}"
  become: true

- name: "USERS - Deposit ssh key"
  ansible.posix.authorized_key:
    user: "{{ item['name'] }}"
    state: "present"
    key: "{{ lookup('file', './files/ssh_keys/' ~ item['name'] ~ '.pub') }}"
    path: "/home/{{ item['name'] }}/.ssh/authorized_keys"
    manage_dir: false
  loop: "{{ users_users_list }}"
  when: item['ssh_key'] is defined and item['ssh_key'] is true and item['state'] | default('present') != 'absent'
