---

galaxy_info:
  author: Mathis
  role_name: openssh
  namespace: mbellamy
  description: Openssh configuration
  company: none
  license: MLP2
  galaxy_tags:
    - openssh
  min_ansible_version: '2.10'
dependencies: []
