---

### To move in a secret manager when possible
- name: "peer_configuration.yml | Check if shared key exists with this peer"
  ansible.builtin.stat:
    path: "{{ wireguard_conf_path }}/{{ peer['name'] }}_shared_key.psk"
  register: _wireguard_shared_key_stat
  become: true

- name: "peer_configuration.yml | Generate shared_key if inexistant"
  ansible.builtin.shell: "wg genpsk > {{ peer['name'] }}_shared_key.psk"
  args:
    chdir: "{{ wireguard_conf_path }}"
  when: not _wireguard_shared_key_stat['stat']['exists']
  become: true

- name: "peer_configuration.yml | Set permissions on shared key"
  ansible.builtin.file:
    path: "{{ wireguard_conf_path }}/{{ peer['name'] }}_shared_key.psk"
    owner: root
    group: root
    mode: '0600'
  become: true

- name: "server_configuration.yml | Get shared key content"
  slurp:
    src: "{{ wireguard_conf_path }}/{{ peer['name'] }}_shared_key.psk"
  register: _wireguard_shared_key_slurp
  become: true

- name: "server_configuration.yml | Set facts"
  set_fact:
    _wireguard_shared_keys_list: "{{ _wireguard_shared_keys_list | default({}) | combine({ peer['name']: _wireguard_shared_key_slurp.content | b64decode}) }}"
  become: true
