---

users_groups_list: "{{ users_groups_list_default | default([])
                    + users_groups_list_dist | default([]) }}"

users_users_list: "{{ users_users_list_default | default([])
                    + users_users_list_dist | default([]) }}"
